services:
  - type: web
    name: chat-reactivo
    env: java
    plan: free
    buildCommand: "./mvnw clean install -DskipTests"
    startCommand: "java -jar target/chat-reactivo-0.0.1-SNAPSHOT.jar.original"
