spring:
  application:
    name: chat-reactivo
  r2dbc:
    url: ${DATABASE_URL:r2dbc:postgresql://localhost:5432/chat_reactivo}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  sql:
    init:
      mode: never

logging:
  level:
    io.r2dbc.postgresql.QUERY: INFO
    io.r2dbc.postgresql.PARAM: INFO

server:
  port: ${PORT:8080}